import { contextBridge, ipcRenderer } from 'electron';

// Expose protected methods that allow the renderer process to use
// the ipcRenderer without exposing the entire object
contextBridge.exposeInMainWorld('electronAPI', {
  // Database operations
  db: {
    auth: {
      login: (username: string, password?: string) => ipcRenderer.invoke('db:auth:login', username, password),
      verifyAdminPassword: (password: string) => ipcRenderer.invoke('db:auth:verifyAdminPassword', password),
    },
    users: {
      getAll: (companyId?: number) => ipcRenderer.invoke('db:users:getAll', companyId),
      getById: (id: number) => ipcRenderer.invoke('db:users:getById', id),
      create: (user: any) => ipcRenderer.invoke('db:users:create', user),
      update: (id: number, user: any) => ipcRenderer.invoke('db:users:update', id, user),
      delete: (id: number) => ipcRenderer.invoke('db:users:delete', id),
      resetPassword: (id: number, newPassword?: string) => ipcRenderer.invoke('db:users:resetPassword', id, newPassword),
    },
    companies: {
      getAll: () => ipcRenderer.invoke('db:companies:getAll'),
      getById: (id: number) => ipcRenderer.invoke('db:companies:getById', id),
      create: (company: any) => ipcRenderer.invoke('db:companies:create', company),
      update: (id: number, company: any) => ipcRenderer.invoke('db:companies:update', id, company),
      delete: (id: number) => ipcRenderer.invoke('db:companies:delete', id),
    },
    customers: {
      getAll: (companyId: number) => ipcRenderer.invoke('db:customers:getAll', companyId),
      getById: (id: number) => ipcRenderer.invoke('db:customers:getById', id),
      getUnpaidInvoices: (customerId: number, companyId?: number) => ipcRenderer.invoke('db:customers:getUnpaidInvoices', customerId, companyId),
      create: (customer: any) => ipcRenderer.invoke('db:customers:create', customer),
      update: (id: number, customer: any) => ipcRenderer.invoke('db:customers:update', id, customer),
      delete: (id: number) => ipcRenderer.invoke('db:customers:delete', id),
      deleteMultiple: (ids: number[]) => ipcRenderer.invoke('db:customers:deleteMultiple', ids),
    },
    vendors: {
      getAll: (companyId: number) => ipcRenderer.invoke('db:vendors:getAll', companyId),
      getById: (id: number) => ipcRenderer.invoke('db:vendors:getById', id),
      create: (vendor: any) => ipcRenderer.invoke('db:vendors:create', vendor),
      update: (id: number, vendor: any) => ipcRenderer.invoke('db:vendors:update', id, vendor),
      delete: (id: number) => ipcRenderer.invoke('db:vendors:delete', id),
      deleteMultiple: (ids: number[]) => ipcRenderer.invoke('db:vendors:deleteMultiple', ids),
    },
    brands: {
      getAll: () => ipcRenderer.invoke('db:brands:getAll'),
      getById: (id: number) => ipcRenderer.invoke('db:brands:getById', id),
      create: (brand: any) => ipcRenderer.invoke('db:brands:create', brand),
      update: (id: number, brand: any) => ipcRenderer.invoke('db:brands:update', id, brand),
      delete: (id: number) => ipcRenderer.invoke('db:brands:delete', id),
      deleteMultiple: (ids: number[]) => ipcRenderer.invoke('db:brands:deleteMultiple', ids),
      deleteAll: () => ipcRenderer.invoke('db:brands:deleteAll'),
    },
    items: {
      getAll: (companyId: number) => ipcRenderer.invoke('db:items:getAll', companyId),
      getById: (id: number) => ipcRenderer.invoke('db:items:getById', id),
      create: (item: any) => ipcRenderer.invoke('db:items:create', item),
      update: (id: number, item: any) => ipcRenderer.invoke('db:items:update', id, item),
      delete: (id: number) => ipcRenderer.invoke('db:items:delete', id),
      deleteMultiple: (ids: number[]) => ipcRenderer.invoke('db:items:deleteMultiple', ids),
      deleteAll: () => ipcRenderer.invoke('db:items:deleteAll'),
      getNextCode: () => ipcRenderer.invoke('db:items:getNextCode'),
    },
    salesInvoices: {
      getAll: (companyId: number, filters?: any) => ipcRenderer.invoke('db:salesInvoices:getAll', companyId, filters),
      getById: (id: number) => ipcRenderer.invoke('db:salesInvoices:getById', id),
      getNextNumber: (companyId: number, fiscalYear?: number | string, isGstEnabled?: boolean) => ipcRenderer.invoke('db:salesInvoices:getNextNumber', companyId, fiscalYear, isGstEnabled),
      getNextPoNumber: (companyId: number, fiscalYear?: number | string) => ipcRenderer.invoke('db:salesInvoices:getNextPoNumber', companyId, fiscalYear),
      create: (invoice: any) => ipcRenderer.invoke('db:salesInvoices:create', invoice),
      update: (id: number, invoice: any) => ipcRenderer.invoke('db:salesInvoices:update', id, invoice),
      delete: (id: number) => ipcRenderer.invoke('db:salesInvoices:delete', id),
      createFromQuotation: (quotationId: number, createdBy?: number, fiscalYear?: number | string, force: boolean = false) => ipcRenderer.invoke('db:salesInvoices:createFromQuotation', quotationId, createdBy, fiscalYear, force),
      createFromChallan: (challanId: number, createdBy?: number, fiscalYear?: number | string, force: boolean = false) => ipcRenderer.invoke('db:salesInvoices:createFromChallan', challanId, createdBy, fiscalYear, force),
      getSalesByItem: (companyId: number, filters?: any) => ipcRenderer.invoke('db:salesInvoices:getSalesByItem', companyId, filters),
      getPendingWithItems: (companyId: number, filters?: any) => ipcRenderer.invoke('db:salesInvoices:getPendingWithItems', companyId, filters),
    },
    salesQuotations: {
      getAll: (companyId: number, filters?: any) => ipcRenderer.invoke('db:salesQuotations:getAll', companyId, filters),
      getById: (id: number) => ipcRenderer.invoke('db:salesQuotations:getById', id),
      getNextNumber: (companyId: number, fiscalYear?: number | string) => ipcRenderer.invoke('db:salesQuotations:getNextNumber', companyId, fiscalYear),
      create: (quotation: any) => ipcRenderer.invoke('db:salesQuotations:create', quotation),
      update: (id: number, quotation: any) => ipcRenderer.invoke('db:salesQuotations:update', id, quotation),
      delete: (id: number) => ipcRenderer.invoke('db:salesQuotations:delete', id),
    },
      deliveryChallans: {
      getAll: (companyId: number) => ipcRenderer.invoke('db:deliveryChallans:getAll', companyId),
      getById: (id: number) => ipcRenderer.invoke('db:deliveryChallans:getById', id),
      getNextNumber: (companyId: number, fiscalYear?: number | string) => ipcRenderer.invoke('db:deliveryChallans:getNextNumber', companyId, fiscalYear),
      getNextPoNumber: (companyId: number, fiscalYear?: number | string) => ipcRenderer.invoke('db:deliveryChallans:getNextPoNumber', companyId, fiscalYear),
      create: (challan: any) => ipcRenderer.invoke('db:deliveryChallans:create', challan),
      update: (id: number, challan: any) => ipcRenderer.invoke('db:deliveryChallans:update', id, challan),
      delete: (id: number) => ipcRenderer.invoke('db:deliveryChallans:delete', id),
      createFromInvoice: (invoiceId: number, createdBy?: number, fiscalYear?: number | string, force: boolean = false) => ipcRenderer.invoke('db:deliveryChallans:createFromInvoice', invoiceId, createdBy, fiscalYear, force),
      createFromQuotation: (quotationId: number, createdBy?: number, selectedItems?: any[], poNumber?: string, fiscalYear?: number | string, force: boolean = false) =>
        ipcRenderer.invoke('db:deliveryChallans:createFromQuotation', quotationId, createdBy, selectedItems, poNumber, fiscalYear, force),
      getChallansByItem: (companyId: number, filters?: any) => ipcRenderer.invoke('db:deliveryChallans:getChallansByItem', companyId, filters),
    },
    purchaseInvoices: {
      getAll: (companyId: number, filters?: any) => ipcRenderer.invoke('db:purchaseInvoices:getAll', companyId, filters),
      getById: (id: number) => ipcRenderer.invoke('db:purchaseInvoices:getById', id),
      getNextNumber: (companyId: number, fiscalYear?: number) => ipcRenderer.invoke('db:purchaseInvoices:getNextNumber', companyId, fiscalYear),
      create: (invoice: any) => ipcRenderer.invoke('db:purchaseInvoices:create', invoice),
      update: (id: number, invoice: any) => ipcRenderer.invoke('db:purchaseInvoices:update', id, invoice),
      delete: (id: number) => ipcRenderer.invoke('db:purchaseInvoices:delete', id),
    },
    expenses: {
      getAll: (companyId: number, filters?: any) => ipcRenderer.invoke('db:expenses:getAll', companyId, filters),
      getById: (id: number) => ipcRenderer.invoke('db:expenses:getById', id),
      create: (expense: any) => ipcRenderer.invoke('db:expenses:create', expense),
      update: (id: number, expense: any) => ipcRenderer.invoke('db:expenses:update', id, expense),
      delete: (id: number) => ipcRenderer.invoke('db:expenses:delete', id),
      getCategories: (companyId: number) => ipcRenderer.invoke('db:expenses:getCategories', companyId),
      createCategory: (category: any) => ipcRenderer.invoke('db:expenses:createCategory', category),
    },
    payments: {
      getAll: (companyId: number, filters?: any) => ipcRenderer.invoke('db:payments:getAll', companyId, filters),
      getByInvoice: (type: string, id: number) => ipcRenderer.invoke('db:payments:getByInvoice', type, id),
      create: (payment: any) => ipcRenderer.invoke('db:payments:create', payment),
      update: (id: number, payment: any) => ipcRenderer.invoke('db:payments:update', id, payment),
      delete: (id: number) => ipcRenderer.invoke('db:payments:delete', id),
    },
    dashboard: {
      getKPIs: (companyId: number, filters?: any) => ipcRenderer.invoke('db:dashboard:getKPIs', companyId, filters),
      getHistory: (companyId: number, filters?: any) => ipcRenderer.invoke('db:dashboard:getHistory', companyId, filters),
      getSalesVsPurchase: (companyId: number, filters?: any) => ipcRenderer.invoke('db:dashboard:getSalesVsPurchase', companyId, filters),
      getExpenseBreakdown: (companyId: number, filters?: any) => ipcRenderer.invoke('db:dashboard:getExpenseBreakdown', companyId, filters),
      getMonthlyRevenue: (companyId: number, filters?: any) => ipcRenderer.invoke('db:dashboard:getMonthlyRevenue', companyId, filters),
      getTopCustomers: (companyId: number, filters?: any) => ipcRenderer.invoke('db:dashboard:getTopCustomers', companyId, filters),
    },
    adjustmentNotes: {
      getAll: (companyId: number, filters?: any) => ipcRenderer.invoke('db:adjustmentNotes:getAll', companyId, filters),
      getById: (id: number) => ipcRenderer.invoke('db:adjustmentNotes:getById', id),
      getNextNumber: (companyId: number, fiscalYear?: number | string) => ipcRenderer.invoke('db:adjustmentNotes:getNextNumber', companyId, fiscalYear),
      create: (note: any) => ipcRenderer.invoke('db:adjustmentNotes:create', note),
      update: (id: number, note: any) => ipcRenderer.invoke('db:adjustmentNotes:update', id, note),
      delete: (id: number) => ipcRenderer.invoke('db:adjustmentNotes:delete', id),
    },
    search: {
      global: (companyId: number, query: string) => ipcRenderer.invoke('db:search:global', companyId, query),
    },
    warehouses: {
      getAll: (companyId: number) => ipcRenderer.invoke('db:warehouses:getAll', companyId),
      create: (warehouse: any) => ipcRenderer.invoke('db:warehouses:create', warehouse),
      update: (id: number, warehouse: any) => ipcRenderer.invoke('db:warehouses:update', id, warehouse),
      delete: (id: number) => ipcRenderer.invoke('db:warehouses:delete', id),
      deleteMultiple: (ids: number[]) => ipcRenderer.invoke('db:warehouses:deleteMultiple', ids),
    },
    customReports: {
      getAll: (companyId: number) => ipcRenderer.invoke('db:customReports:getAll', companyId),
      create: (report: any) => ipcRenderer.invoke('db:customReports:create', report),
      delete: (id: number) => ipcRenderer.invoke('db:customReports:delete', id),
    },
    heartbeat: () => ipcRenderer.invoke('db:heartbeat'),
    config: {
      get: () => ipcRenderer.invoke('db:config:get'),
      save: (config: any) => ipcRenderer.invoke('db:config:save', config),
    },
    files: {
      save: (base64Data: string, fileName: string, subDir: string) => ipcRenderer.invoke('file:save', base64Data, fileName, subDir),
      readAsDataURL: (path: string) => ipcRenderer.invoke('file:readAsDataURL', path),
      printToPDF: () => ipcRenderer.invoke('file:printToPDF'),
      getSavePath: (defaultName: string) => ipcRenderer.invoke('file:getSavePath', defaultName),
      captureAndSave: (filePath: string, heightMM?: number) => ipcRenderer.invoke('file:captureAndSave', filePath, heightMM),
      printHtmlToPDF: (html: string, filePath: string, heightMM: number) => ipcRenderer.invoke('file:printHtmlToPDF', html, filePath, heightMM),
      print: () => ipcRenderer.invoke('file:print'),
    },
    settings: {
      getAll: () => ipcRenderer.invoke('db:settings:getAll'),
      get: (key: string) => ipcRenderer.invoke('db:settings:get', key),
      set: (key: string, value: string) => ipcRenderer.invoke('db:settings:set', key, value),
    },
  },
  // Menu actions
  onMenuAction: (callback: (action: string) => void) => {
    ipcRenderer.on('menu-action', (event, action) => callback(action));
  },
  // App Restart
  appRestart: () => ipcRenderer.invoke('app:restart'),
  // Platform info
  platform: process.platform,
});
